import math

# --- ECRAN ---
COULEUR_FOND = "lightsalmon"
BARRES_COULEUR_FOND = "lightsalmon"
ACTION_BAR_COULEUR_BOUTONS = "seashell"

# LARGEURS BARRES
LARGEUR_ACTION_BAR = 220
LARGEUR_RESULTAT_BAR = 220

# --- CONFIGURATION GRILLE ---
# NB_COL et NB_LIG sont calculés dynamiquement
HEX_COTE = 25
HEX_HAUTEUR = math.sqrt(3) * HEX_COTE
GRILLE_COULEUR_FOND = "papayawhip"

# --- COULEURS ---
COULEUR_MUR = "black"
COULEUR_DEPART = "magenta"
COULEUR_ARRIVEE = "red"
COULEUR_DEFAUT = "papayawhip"
COULEUR_CHEMIN_FINAL = "red"
COULEUR_FLECHE = "black"
COULEUR_FORET = "green"
COULEUR_SABLE = "yellow"
COULEUR_EAU = "steelblue"
COULEUR_GLACE = "lightcyan"

# --- TYPES ---
TYPE_MUR = 1000000000000000000000000
TYPE_DEFAUT = 1
TYPE_FORET = 3
TYPE_SABLE = 5
TYPE_EAU = 10
TYPE_GLACE = -1

# --- ANIMATION ---
DELAI_VAGUE = 150
DELAI_CHEMIN = 150

# --- Aléatoire ---
NOMBRE_TERRAIN_MAXIMUM = 140